services:
  # 🟢 MongoDB Service
  mongo:
    image: mongo:latest                # Official MongoDB image
    container_name: mongo_database
    ports:
      - "27017:27017"                  # Mongo Port
    volumes:
      - mongo_data:/data/db                # Persist DB data locally
    environment:                       # For root DB user setup
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: atec123
    networks:
      - backend-network

volumes:
  mongo_data:
# 🌐 Shared Network for Communication
networks:
  backend-network:                   # Name of the shared network
    driver: bridge
